#!/bin/bash

# echo $1 $2


# read -p "好きな食べ物なんですか？" food

# echo "I like ${food}です"


# # $の区別をつけるためには{}をつける




# hobby=(baseball soccder ultimate)


# echo ${hobby[0]}

# echo ${hobby[@]}

# echo ${#hobby[@]}



# echo $((5 + 6))


# read -p "数字を入力してください  " num


# if (( num > 10 )) ; then


#   echo "$num"



# fi



# for i in {1..10} ; do

#  echo $i

# done


# (( i=0 ))

# while (( i < 10 )) ; do


#   echo "$i"
#   (( i++ ))
# done




# while read line ; do

#   echo "$line"

# done

# read lineでファイルの行を指定することが可能



read -p "好きな食べ物なにですか？  " food

case "$food" in

sushi)
 echo "good"

;;


*)

 echo "bad"



esac
